import React, { useState } from "react";
import { Card } from "@/components/ui/card";
import { Pagination, PaginationContent, PaginationEllipsis, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from "@/components/ui/pagination";
import { NavLink } from "react-router-dom";

// Dummy data for demonstration
const ongoingAnimes = [
  {
    title: "Boku no Tsuma wa Kanjou ga Nai",
    link: "https://otakudesu.cloud/anime/boku-tsuma-kanjou-nai-sub-indo/",
    episode: "Episode 6",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Boku-no-Tsuma-wa-Kanjou-ga-Nai.jpg",
    image_alt: "Boku no Tsuma wa Kanjou ga Nai Sub Indo",
    date_release: "07 Agu",
    day_release: "Random",
  },
  {
    title: "Isekai Shikkaku",
    link: "https://otakudesu.cloud/anime/isekai-sikaku-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Isekai-Shikkaku.jpg",
    image_alt: "Isekai Shikkaku Sub Indo",
    date_release: "07 Agu",
    day_release: "Rabu",
  },
  {
    title: "Katsute Mahou Shoujo to Aku wa Tekitai shiteita.",
    link: "https://otakudesu.cloud/anime/katsute-mahou-sheteita-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Katsute-Mahou-Shoujo-to-Aku-wa-Tekitai-shiteita..jpg",
    image_alt: "Katsute Mahou Shoujo to Aku wa Tekitai shiteita. Sub Indo",
    date_release: "07 Agu",
    day_release: "Selasa",
  },
  {
    title: "Na Nare Hana Nare",
    link: "https://otakudesu.cloud/anime/nare-hana-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/143526.jpg",
    image_alt: "Na Nare Hana Nare Sub Indo",
    date_release: "06 Agu",
    day_release: "Senin",
  },
  {
    title: "Kimi ni Todoke Season 3",
    link: "https://otakudesu.cloud/anime/kimi-todoke-s3-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/08/Kimi-ni-Todoke-s3.jpg",
    image_alt: "Kimi ni Todoke S3 Sub Indo",
    date_release: "06 Agu",
    day_release: "None",
  },
  {
    title: "VTuber Nandaga Haishin Kiri Wasuretara Densetsu ni Natteta",
    link: "https://otakudesu.cloud/anime/vtuber-nankiritara-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/VTuber-Nandaga-Haishin-Kiri-Wasuretara-Densetsu-ni-Natteta.jpg",
    image_alt: "VTuber Nandaga Haishin Kiri Wasuretara Densetsu ni Natteta Sub Indo",
    date_release: "05 Agu",
    day_release: "Senin",
  },
  {
    title: "Isekai Yururi Kikou",
    link: "https://otakudesu.cloud/anime/isekai-yuru-kikou-sub-indo/",
    episode: "Episode 6",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Isekai-Yururi-Kikou.jpg",
    image_alt: "Isekai Yururi Kikou Sub Indo",
    date_release: "05 Agu",
    day_release: "Senin",
  },
  {
    title: "Fairy Tail: 100-nen Quest",
    link: "https://otakudesu.cloud/anime/fairy-tail-100-quest-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/144083.jpg",
    image_alt: "Fairy Tail: 100-nen Quest Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "Yozakura-san Chi no Daisakusen",
    link: "https://otakudesu.cloud/anime/yozakura-daisakusen-sub-indo/",
    episode: "Episode 18",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Yozakura-san-Chi-no-Daisakusen.jpg",
    image_alt: "Yozakura-san Chi no Daisakusen Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "Tsue to Tsurugi no Wistoria",
    link: "https://otakudesu.cloud/anime/tsue-tsurugi-wistoria-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/142263.jpg",
    image_alt: "Tsue to Tsurugi no Wistoria Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "One Piece",
    link: "https://otakudesu.cloud/anime/opiece-sub-indo/",
    episode: "Episode 1114",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2021/05/One-Piece-Sub-Indo.jpg",
    image_alt: "One Piece Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "Nige Jouzu no Wakagimi",
    link: "https://otakudesu.cloud/anime/nige-wakagimi-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/140401.jpg",
    image_alt: "Nige Jouzu no Wakagimi Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "Shoushimin Series",
    link: "https://otakudesu.cloud/anime/shoushimin-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Shoushimin-Series.jpg",
    image_alt: "Shoushimin Series Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "The Fable",
    link: "https://otakudesu.cloud/anime/fable-sub-indo/",
    episode: "Episode 18",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/The-Fable.jpg",
    image_alt: "The Fable Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "Atri: My Dear Moments",
    link: "https://otakudesu.cloud/anime/atri-my-dear-moments-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Atri.jpg",
    image_alt: "Atri: My Dear Moments Sub Indo",
    date_release: "04 Agu",
    day_release: "None",
  },
  {
    title: "Naze Boku no Sekai wo Daremo Oboeteinai no ka?",
    link: "https://otakudesu.cloud/anime/naze-bokusekai-daremo-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Naze-Boku-no-Sekai-wo-Daremo-Oboeteinai-no-ka.jpg",
    image_alt: "Naze Boku no Sekai wo Daremo Oboeteinai no ka? Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "Make Heroine ga Oosugiru!",
    link: "https://otakudesu.cloud/anime/heroine-oosugiru-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Make-Heroine-ga-Oosugiru.jpg",
    image_alt: "Make Heroine ga Oosugiru! Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "Monogatari Series: Off & Monster Season",
    link: "https://otakudesu.cloud/anime/monogatari-monster-season-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/140952.jpg",
    image_alt: "Monogatari Series: Off & Monster Season Sub indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "Tensui no Sakuna-hime",
    link: "https://otakudesu.cloud/anime/tensui-sakuna-hime-sub-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Tensui-no-Sakuna-hime.jpg",
    image_alt: "Tensui no Sakuna-hime Sub Indo",
    date_release: "04 Agu",
    day_release: "Minggu",
  },
  {
    title: "Mob kara Hajimaru Tansaku Eiyuutan",
    link: "https://otakudesu.cloud/anime/mob-hajimaru-eiyutan-sub-indo/",
    episode: "Episode 6",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/143664.jpg",
    image_alt: "Mob kara Hajimaru Tansaku Eiyuutan Sub Indo",
    date_release: "03 Agu",
    day_release: "Sabtu",
  },
  {
    title: "Madougushi Dahliya wa Utsumukanai",
    link: "https://otakudesu.cloud/anime/madougushi-dahliya-utsumukanai-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Madougushi-Dahliya-wa-Utsumukanai.jpg",
    image_alt: "Madougushi Dahliya wa Utsumukanai Sub Indo",
    date_release: "03 Agu",
    day_release: "Sabtu",
  },
  {
    title: "Boku no Hero Academia Season 7",
    link: "https://otakudesu.cloud/anime/bnha-season-7-sub-ind/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/05/Boku-no-Hero-Academia-Season-7.jpg",
    image_alt: "Boku no Hero Academia Season 7 Sub Indo",
    date_release: "03 Agu",
    day_release: "Sabtu",
  },
  {
    title: "NieR:Automata Ver1.1a Part 2",
    link: "https://otakudesu.cloud/anime/niermata-ver1-p2-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/143539.jpg",
    image_alt: "NieR:Automata Ver1.1a Part 2 Sub Indo",
    date_release: "03 Agu",
    day_release: "Sabtu",
  },
  {
    title: "Bye Bye, Earth",
    link: "https://otakudesu.cloud/anime/bye-earth-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/bye-bye-earth.jpg",
    image_alt: "Bye Bye, Earth Sub Indo",
    date_release: "03 Agu",
    day_release: "Jumat",
  },
  {
    title: "Tensei shitara Slime Datta Ken Season 3",
    link: "https://otakudesu.cloud/anime/tensei-shitara-slime-datta-season-3-sub-indo/",
    episode: "Episode 17",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/03/Tensei-shitara-Slime-Datta-Ken-Season-3.jpg",
    image_alt: "Tensei shitara Slime Datta Ken Season 3 Sub Indo",
    date_release: "03 Agu",
    day_release: "Sabtu",
  },
  {
    title: "2.5-jigen no Ririsa",
    link: "https://otakudesu.cloud/anime/2-5-jigen-ririsa-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/2.5-jigen-no-Ririsa.jpg",
    image_alt: "",
    date_release: "02 Agu",
    day_release: "Jumat",
  },
  {
    title: "Code Geass: Dakkan no Rozé",
    link: "https://otakudesu.cloud/anime/cd-geass-dakkan-roze-sub-indo/",
    episode: "Episode 7",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/06/Code-Geass.jpg",
    image_alt: "Code Geass: Dakkan no Rozé Sub Indo",
    date_release: "02 Agu",
    day_release: "Jumat",
  },
  {
    title: "Megami no Cafe Terrace Season 2",
    link: "https://otakudesu.cloud/anime/megami-cafece-s2-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Megami-no-Cafe-Terrace-Season-2.jpg",
    image_alt: "Megami no Cafe Terrace Season 2 Sub Indo",
    date_release: "02 Agu",
    day_release: "Jumat",
  },
  {
    title: 'Hazurewaku no "Joutai Ijou Skill" de Saikyou ni Natta Ore ga Subete wo Juurin suru made',
    link: "https://otakudesu.cloud/anime/joutai-ijou-skill-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Joutai-Ijou-Skill.jpg",
    image_alt: "Joutai Ijou Skill Sub Indo",
    date_release: "02 Agu",
    day_release: "Jumat",
  },
  {
    title: 'Ore wa Subete wo "Parry" suru',
    link: "https://otakudesu.cloud/anime/ore-subete-parry-suru-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Ore-wa-Subete-wo-Parry-suru.jpg",
    image_alt: 'Ore wa Subete wo "Parry" suru Sub Indo',
    date_release: "02 Agu",
    day_release: "Jumat",
  },
  {
    title: "Giji Harem",
    link: "https://otakudesu.cloud/anime/giji-harem-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Giji-Harem.jpg",
    image_alt: "Giji Harem Sub Indo",
    date_release: "02 Agu",
    day_release: "Jumat",
  },
  {
    title: "Gimai Seikatsu",
    link: "https://otakudesu.cloud/anime/gise-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/143707.jpg",
    image_alt: "Gimai Seikatsu Sub Indo",
    date_release: "01 Agu",
    day_release: "Kamis",
  },
  {
    title: "Oshi no Ko Season 2",
    link: "https://otakudesu.cloud/anime/oshi-ko-s2-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/143302.jpg",
    image_alt: "Oshi no Ko Season 2 Sub Indo",
    date_release: "01 Agu",
    day_release: "Rabu",
  },
  {
    title: "Isekai Suicide Squad",
    link: "https://otakudesu.cloud/anime/suicide-squad-sub-indo/",
    episode: "Episode 8",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/06/Isekai-Suicide-Squad.jpg",
    image_alt: "Isekai Suicide Squad Sub Indo",
    date_release: "01 Agu",
    day_release: "Kamis",
  },
  {
    title: "Shikanoko Nokonoko Koshitantan",
    link: "https://otakudesu.cloud/anime/shikanoko-nokotan-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Shikanoko-Nokonoko-Koshitantan.jpg",
    image_alt: "Shikanoko Nokonoko Koshitantan Sub Indo",
    date_release: "01 Agu",
    day_release: "Jumat",
  },
  {
    title: "Koi wa Futago de Warikirenai",
    link: "https://otakudesu.cloud/anime/koi-futago-warikirenai-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/142250.jpg",
    image_alt: "Koi wa Futago de Warikirenai Sub Indo",
    date_release: "01 Agu",
    day_release: "Kamis",
  },
  {
    title: "Sengoku Youko: Senma Konton-hen",
    link: "https://otakudesu.cloud/anime/sengoku-youko-s2-sub-indo/",
    episode: "Episode 3",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Sengoku-Youko-Senam-Konton.jpg",
    image_alt: "Sengoku Youko: Senam Konton Sub Indo",
    date_release: "01 Agu",
    day_release: "Kamis",
  },
  {
    title: "Kimisen Season 2",
    link: "https://otakudesu.cloud/anime/kimi-boku-saigo-senjou-s2-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Kimi-to-Boku-no-Saigo-no-Senjou-Aruiwa-Sekai-ga-Hajimaru-Seisen-Season-2.jpg",
    image_alt: "Kimisen Season 2 Sub Indo",
    date_release: "01 Agu",
    day_release: "Rabu",
  },
  {
    title: "Maougun Saikyou no Majutsushi wa Ningen datta",
    link: "https://otakudesu.cloud/anime/maougun-saikyou-majutsushi-ningen-sub-indo/",
    episode: "Episode 6",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/06/142013.jpg",
    image_alt: "Maougun Saikyou no Majutsushi wa Ningen datta Sub Indo",
    date_release: "31 Jul",
    day_release: "Kamis",
  },
  {
    title: "Tokidoki Bosotto Russia-go de Dereru Tonari no Alya-san",
    link: "https://otakudesu.cloud/anime/tokidoki-bosotto-russia-alya-san-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Tokidoki-Bosotto-Russia-go-de-Dereru-Tonari-no-Alya-san.jpg",
    image_alt: "Tokidoki Bosotto Russia-go de Dereru Tonari no Alya-san Sub Indo",
    date_release: "31 Jul",
    day_release: "Kamis",
  },
  {
    title: "Mayonaka Punch",
    link: "https://otakudesu.cloud/anime/myonka-punch-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Mayonaka-Punch.jpg",
    image_alt: "Mayonaka Punch Sub Indo",
    date_release: "31 Jul",
    day_release: "Random",
  },
  {
    title: "Shy Season 2",
    link: "https://otakudesu.cloud/anime/shy-s2-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Shy-S2.jpg",
    image_alt: "Shy Season 2 Sub Indo",
    date_release: "30 Jul",
    day_release: "Senin",
  },
  {
    title: "Ookami to Koushinryou: Merchant Meets the Wise Wolf",
    link: "https://otakudesu.cloud/anime/ookami-koushinryou-2024-sub-indo/",
    episode: "Episode 18",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Ookami-to-Koushinryou.jpg",
    image_alt: "Ookami to Koushinryou Sub Indo",
    date_release: "30 Jul",
    day_release: "Selasa",
  },
  {
    title: "Shinmai Ossan Boukensha",
    link: "https://otakudesu.cloud/anime/shinmai-ossan-boukensha-sub-indo/",
    episode: "Episode 5",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Shinmai-Ossan-Boukensha.jpg",
    image_alt: "Shinmai Ossan Boukensha Sub Indoi",
    date_release: "30 Jul",
    day_release: "Selasa",
  },
  {
    title: "Senpai wa Otokonoko",
    link: "https://otakudesu.cloud/anime/senpai-otokonoko-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Senpai-wa-Otokonoko.jpg",
    image_alt: "Senpai wa Otokonoko Sub Indo",
    date_release: "28 Jul",
    day_release: "Jumat",
  },
  {
    title: "Kono Sekai wa Fukanzen Sugiru",
    link: "https://otakudesu.cloud/anime/kono-sekai-fukanzen-sugiru-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Kono-Sekai-wa-Fukanzen-Sugiru.jpg",
    image_alt: "Kono Sekai wa Fukanzen Sugiru Sub Indo",
    date_release: "27 Jul",
    day_release: "Sabtu",
  },
  {
    title: "Dungeon no Naka no Hito",
    link: "https://otakudesu.cloud/anime/dungeon-people-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/Dungeon-no-Naka-no-Hito.jpg",
    image_alt: "Dungeon no Naka no Hito Sub Indo",
    date_release: "27 Jul",
    day_release: "Sabtu",
  },
  {
    title: "Maou Gakuin no Futekigousha Season 2 Part 2",
    link: "https://otakudesu.cloud/anime/maou-gakuin-futekigousha-s2-p2-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Maou-Gakuin-no-Futekigousha-Season-2-Part-2.png",
    image_alt: "Maou Gakuin no Futekigousha Season 2 Part 2 Sub Indo",
    date_release: "25 Jul",
    day_release: "Sabtu",
  },
  {
    title: "Tasuuketsu",
    link: "https://otakudesu.cloud/anime/tasuketsu-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/07/143629.jpg",
    image_alt: "Tasuuketsu Sub Indo",
    date_release: "24 Jul",
    day_release: "Rabu",
  },
  {
    title: "Karasu wa Aruji wo Erabanai",
    link: "https://otakudesu.cloud/anime/karasu-aruji-erabanai-sub-indo/",
    episode: "Episode 14",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Karasu-wa-Aruji-wo-Erabanai.jpg",
    image_alt: "Karasu wa Aruji wo Erabanai Sub Indo",
    date_release: "21 Jul",
    day_release: "Minggu",
  },
  {
    title: "Shinigami Bocchan to Kuro Maid Season 3",
    link: "https://otakudesu.cloud/anime/shimaid-s3-sub-indo-2/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Shinigami-Bocchan-to-Kuro-Maid-Season-3.jpg",
    image_alt: "Shinigami Bocchan to Kuro Maid Season 3 Sub Indo",
    date_release: "03 Jul",
    day_release: "None",
  },
  {
    title: "Sasayaku You ni Koi wo Utau",
    link: "https://otakudesu.cloud/anime/sasayaku-you-koi-utau-sub-indo/",
    episode: "Episode 10",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Sasayaku-You-ni-Koi-wo-Utau.jpg",
    image_alt: "Sasayaku You ni Koi wo Utau Sub Indo",
    date_release: "01 Jul",
    day_release: "Minggu",
  },
  {
    title: "The iDOLM@STER Shiny Colors",
    link: "https://otakudesu.cloud/anime/the-imas-shiny-colors-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/The-iDOLM@STER-Shiny-Colors.jpg",
    image_alt: "The iDOLM@STER Shiny Colors Sub Indo",
    date_release: "01 Jul",
    day_release: "None",
  },
  {
    title: "Kimetsu no Yaiba: Hashira Geiko-hen",
    link: "https://otakudesu.cloud/anime/kimetsu-yaiba-s4-sub-indo/",
    episode: "Episode 8",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/05/Kimetsu-no-Yaiba-Hashira-Geiko-hen.jpg",
    image_alt: "Kimetsu no Yaiba Hashira Geiko-hen Sub Indo",
    date_release: "01 Jul",
    day_release: "None",
  },
  {
    title: "Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2",
    link: "https://otakudesu.cloud/anime/mushoku-tensi-s2-part-2-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Mushoku-Tensei-II-Isekai-Ittara-Honki-Dasu-Part-2.jpg",
    image_alt: "Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2 Sub Indo",
    date_release: "01 Jul",
    day_release: "None",
  },
  {
    title: "Hibike! Euphonium Season 3",
    link: "https://otakudesu.cloud/anime/hibike-euphonium-season-3-subtitle-indonesia/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Hibike-Euphonium-Season-3-Subtitle-Indonesia.jpg",
    image_alt: "Hibike! Euphonium Season 3 Sub Indo",
    date_release: "30 Jun",
    day_release: "None",
  },
  {
    title: "Sentai Daishikkaku",
    link: "https://otakudesu.cloud/anime/loser-ranger-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Sentai-Daishikkaku.jpg",
    image_alt: "Sentai Daishikkaku Sub Indo",
    date_release: "30 Jun",
    day_release: "None",
  },
  {
    title: "Captain Tsubasa Season 2: Junior Youth-hen",
    link: "https://otakudesu.cloud/anime/captain-tsubasa-s2-sub-indo/",
    episode: "Episode 39",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/10/Captain-Tsubasa-Season-2.jpg",
    image_alt: "Captain Tsubasa Season 2: Junior Youth-hen Sub Indo",
    date_release: "30 Jun",
    day_release: "None",
  },
  {
    title: "The New Gate",
    link: "https://otakudesu.cloud/anime/new-gate-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/The-New-Gate.jpg",
    image_alt: "The New Gate Sub Indo",
    date_release: "30 Jun",
    day_release: "Minggu",
  },
  {
    title: "Kaijuu 8-gou",
    link: "https://otakudesu.cloud/anime/kaiju-eight-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Kaijuu-8-gou.jpg",
    image_alt: "Kaijuu 8-gou Sub Indo",
    date_release: "29 Jun",
    day_release: "None",
  },
  {
    title: "Girls Band Cry",
    link: "https://otakudesu.cloud/anime/gbc-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Girls-Band-Cry.jpg",
    image_alt: "Girls Band Cry Sub Indo",
    date_release: "29 Jun",
    day_release: "None",
  },
  {
    title: "Mahouka Koukou no Rettousei Season 3",
    link: "https://otakudesu.cloud/anime/mahouka-koukou-season-3-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Mahouka-Koukou-no-Rettousei-Season-3.jpg",
    image_alt: "Mahouka Koukou no Rettousei Season 3 Sub Indo",
    date_release: "29 Jun",
    day_release: "None",
  },
  {
    title: "Wind Breaker",
    link: "https://otakudesu.cloud/anime/wind-breaker-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Wind-Breaker.jpg",
    image_alt: "Wind Breaker Sub Indo",
    date_release: "28 Jun",
    day_release: "None",
  },
  {
    title: "Seiyuu Radio no Uraomote",
    link: "https://otakudesu.cloud/anime/seiyu-radio-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Seiyuu-Radio-no-Uraomote.jpg",
    image_alt: "Seiyuu Radio no Uraomote Sub Indo",
    date_release: "27 Jun",
    day_release: "None",
  },
  {
    title: "Kenka Dokugaku",
    link: "https://otakudesu.cloud/anime/kenka-doku-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Kenka-Dokugaku.jpg",
    image_alt: "Kenka Dokugaku Sub Indo",
    date_release: "27 Jun",
    day_release: "None",
  },
  {
    title: "Kaii to Otome to Kamikakushi",
    link: "https://otakudesu.cloud/anime/kai-otome-kamikusi-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/141688.jpg",
    image_alt: "Kaii to Otome to Kamikakushi Sub Indo",
    date_release: "27 Jun",
    day_release: "None",
  },
  {
    title: "Date A Live Season 5",
    link: "https://otakudesu.cloud/anime/date-live-v-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Date-A-Live-V.jpg",
    image_alt: "Date A Live V Sub Indo",
    date_release: "26 Jun",
    day_release: "None",
  },
  {
    title: "Unnamed Memory",
    link: "https://otakudesu.cloud/anime/unnamed-memo-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Unnamed-Memory.jpg",
    image_alt: "Unnamed Memory Sub Indo",
    date_release: "26 Jun",
    day_release: "None",
  },
  {
    title: "Shuumatsu Train Doko e Iku?",
    link: "https://otakudesu.cloud/anime/shuumatsu-train-doko-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Shuumatsu-Train-Doko-e-Iku.jpg",
    image_alt: "Shuumatsu Train Doko e Iku Sub Indo",
    date_release: "25 Jun",
    day_release: "None",
  },
  {
    title: "Tsuki ga Michibiku Isekai Douchuu Season 2",
    link: "https://otakudesu.cloud/anime/tsuki-michibiku-isekai-douchu-s2-sub-indo/",
    episode: "Episode 25",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Tsuki-ga-Michibiku-Isekai-Douchuu-Season-2-Sub-Indo.jpg",
    image_alt: "Tsuki ga Michibiku Isekai Douchuu Season 2 Sub Indo",
    date_release: "25 Jun",
    day_release: "None",
  },
  {
    title: "Lv2 kara Cheat datta Motoyuusha Kouho no Mattari Isekai Life",
    link: "https://otakudesu.cloud/anime/lv2-kara-cheat-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Lv2-kara-Cheat-datta-Motoyuusha-Kouho-no-Mattari-Isekai-Life.jpg",
    image_alt: "Lv2 kara Cheat datta Motoyuusha Kouho no Mattari Isekai Life Sub Indo",
    date_release: "25 Jun",
    day_release: "None",
  },
  {
    title: "Kami wa Game ni Ueteiru.",
    link: "https://otakudesu.cloud/anime/kami-game-ueteiru-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Kami-wa-Game-ni-Ueteiru..jpg",
    image_alt: "Kami wa Game ni Ueteiru. Sub Indo",
    date_release: "24 Jun",
    day_release: "Senin",
  },
  {
    title: "Yoru no Kurage wa Oyogenai",
    link: "https://otakudesu.cloud/anime/yoru-kurage-oyogenai-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/141827.jpg",
    image_alt: "Yoru no Kurage wa Oyogenai Sub Indo",
    date_release: "24 Jun",
    day_release: "None",
  },
  {
    title: "Vampire Dormitory",
    link: "https://otakudesu.cloud/anime/vampir-drom-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Vampire-Dormitory.jpg",
    image_alt: "Vampire Dormitory Sub Indo",
    date_release: "24 Jun",
    day_release: "None",
  },
  {
    title: "Blue Archive the Animation",
    link: "https://otakudesu.cloud/anime/blue-archive-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/140995.jpg",
    image_alt: "Blue Archive the Animation Subtitle Indonesia Sub Indo",
    date_release: "24 Jun",
    day_release: "None",
  },
  {
    title: "Tensei Kizoku, Kantei Skill de Nariagaru",
    link: "https://otakudesu.cloud/anime/tensei-skill-nariagaru-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Tensei-Kizoku-Kantei-Skill-de-Nariagaru.jpg",
    image_alt: "Tensei Kizoku, Kantei Skill de Nariagaru Sub Indo",
    date_release: "24 Jun",
    day_release: "None",
  },
  {
    title: "Kuroshitsuji: Kishuku Gakkou-hen",
    link: "https://otakudesu.cloud/anime/kurositsuji-gakkou-sub-indo/",
    episode: "Episode 11",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Kuroshitsuji-Kishuku-Gakkou-hen.jpg",
    image_alt: "Kuroshitsuji Kishuku Gakkou-hen Sub Indo",
    date_release: "23 Jun",
    day_release: "None",
  },
  {
    title: "Henjin no Salad Bowl",
    link: "https://otakudesu.cloud/anime/henjin-salad-bowl-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Henjin-no-Salad-Bowl.jpg",
    image_alt: "Henjin no Salad Bowl Sub Indo",
    date_release: "21 Jun",
    day_release: "None",
  },
  {
    title: "Hananoi-kun to Koi no Yamai",
    link: "https://otakudesu.cloud/anime/hananoi-koi-yamai-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Hananoi-kun-to-Koi-no-Yamai.jpg",
    image_alt: "Hananoi-kun to Koi no Yamai Sub Indo",
    date_release: "21 Jun",
    day_release: "None",
  },
  {
    title: "Yuru Camp△ Season 3",
    link: "https://otakudesu.cloud/anime/yuru-no-camp-season-3-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Yuru-Camp△-Season-3.jpg",
    image_alt: "Yuru Camp△ Season 3 Sub Indo",
    date_release: "21 Jun",
    day_release: "None",
  },
  {
    title: "Bartender: Kami no Glass",
    link: "https://otakudesu.cloud/anime/brtender-kami-glass-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Bartender-Kami-no-Glass.jpg",
    image_alt: "Bartender Kami no Glass Sub Indo",
    date_release: "20 Jun",
    day_release: "None",
  },
  {
    title: "KonoSuba Season 3",
    link: "https://otakudesu.cloud/anime/konsuba-season-3-sub-indo/",
    episode: "Episode 11",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/03/KonoSuba-Season-3.jpg",
    image_alt: "KonoSuba Season 3 Sub Indo",
    date_release: "20 Jun",
    day_release: "None",
  },
  {
    title: "Tensei shitara Dainana Ouji Datta node",
    link: "https://otakudesu.cloud/anime/tensei-datta-node-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Tensei-shitara-Dainana-Ouji-Datta-node.jpg",
    image_alt: "Tensei shitara Dainana Ouji Datta node Sub Indo",
    date_release: "18 Jun",
    day_release: "None",
  },
  {
    title: "Re:Monster",
    link: "https://otakudesu.cloud/anime/re-mnstr-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/ReMnstr.jpg",
    image_alt: "Re:Monster Sub Indo",
    date_release: "18 Jun",
    day_release: "None",
  },
  {
    title: "Dungeon Meshi",
    link: "https://otakudesu.cloud/anime/dungeon-meshi-sub-indo/",
    episode: "Episode 24",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Dungeon-Meshi.jpg",
    image_alt: "Dungeon Meshi Sub Indo",
    date_release: "17 Jun",
    day_release: "None",
  },
  {
    title: "Jiisan Baasan Wakagaeru",
    link: "https://otakudesu.cloud/anime/jiisan-baasan-sub-indo/",
    episode: "Episode 11",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Jiisan-Baasan-Wakagaeru.jpg",
    image_alt: "Jiisan Baasan Wakagaeru Sub Indo",
    date_release: "17 Jun",
    day_release: "Senin",
  },
  {
    title: "One Room, Hiatari Futsuu, Tenshi-tsuki.",
    link: "https://otakudesu.cloud/anime/one-room-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/03/One-Room.jpg",
    image_alt: "",
    date_release: "16 Jun",
    day_release: "None",
  },
  {
    title: "Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?",
    link: "https://otakudesu.cloud/anime/maou-elf-yome-shitanda-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Maou-no-Ore-ga-Dorei-Elf-wo-Yome-ni-Shitanda-ga.jpg",
    image_alt: "Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii? Sub Indo",
    date_release: "14 Jun",
    day_release: "None",
  },
  {
    title: "Dekisokonai to Yobareta Motoeiyuu",
    link: "https://otakudesu.cloud/anime/dekisoko-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Dekisokonai-to-Yobareta-Motoeiyuu-wa-Jikka-kara-Tsuihou-sareta-node-Sukikatte-ni-Ikiru-Koto-ni-Shita.jpg",
    image_alt: "Dekisoko Sub Indo",
    date_release: "11 Jun",
    day_release: "None",
  },
  {
    title: "Hikari no Ou Season 2",
    link: "https://otakudesu.cloud/anime/hikariou-s2-sub-indo/",
    episode: "Episode 10",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Hikari-no-Ou-Season-2-Sub-Indo.jpg",
    image_alt: "Hikari no Ou Season 2 Sub Indo",
    date_release: "06 Jun",
    day_release: "None",
  },
  {
    title: "Touken Ranbu Kai",
    link: "https://otakudesu.cloud/anime/touken-ranbu-sub-indo/",
    episode: "Episode 8",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Touken-Ranbu-Kai.jpg",
    image_alt: "Touken Ranbu Kai Sub Indo",
    date_release: "22 Mei",
    day_release: "None",
  },
  {
    title: "Yubisaki to Renren",
    link: "https://otakudesu.cloud/anime/yubisaki-renren-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Yubisaki-to-Renren.jpg",
    image_alt: "Yubisaki to Renren Sub Indo",
    date_release: "14 Mei",
    day_release: "None",
  },
  {
    title: "Ninja Kamui",
    link: "https://otakudesu.cloud/anime/ninja-kamui-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/02/Ninja-Kamui.jpg",
    image_alt: "Ninja Kamui Sub Indo",
    date_release: "05 Mei",
    day_release: "None",
  },
  {
    title: "Tonari no Youkai-san",
    link: "https://otakudesu.cloud/anime/tonari-youkai-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/Tonari-no-Youkai-san.jpg",
    image_alt: "Tonari no Youkai-san Sub Indo",
    date_release: "01 Mei",
    day_release: "Random",
  },
  {
    title: "Astro Note",
    link: "https://otakudesu.cloud/anime/astro-n-sub-indo/",
    episode: "Episode 3",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/04/141859.jpg",
    image_alt: "Astron Note Sub Indo",
    date_release: "19 Apr",
    day_release: "Sabtu",
  },
  {
    title: "Kingdom Season 5",
    link: "https://otakudesu.cloud/anime/kngdm-season-5-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Kingdom-Season-5-Subtitle-Indonesia.jpg",
    image_alt: "Kingdom Season 5 Sub Indo",
    date_release: "13 Apr",
    day_release: "None",
  },
  {
    title: "Megumi no Daigo: Kyuukoku no Orange",
    link: "https://otakudesu.cloud/anime/megdaigo-sub-indo/",
    episode: "Episode 19",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/10/Megumi-no-Daigo-Kyuukoku-no-Orange-Subtitle-Indonesia.jpg",
    image_alt: "Megumi no Daigo: Kyuukoku no Orange Sub Indo",
    date_release: "12 Apr",
    day_release: "None",
  },
  {
    title: "Bucchigiri?!",
    link: "https://otakudesu.cloud/anime/bucchigiri-episode-1-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Bucchigiri-Subtitle-Indonesia.jpg",
    image_alt: "Bucchigiri Sub Indo",
    date_release: "09 Apr",
    day_release: "None",
  },
  {
    title: "Majo to Yajuu",
    link: "https://otakudesu.cloud/anime/majo-yajuu-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Majo-to-Yajuu.jpg",
    image_alt: "Majo to Yajuu Sub Indo",
    date_release: "05 Apr",
    day_release: "None",
  },
  {
    title: "Metallic Rouge",
    link: "https://otakudesu.cloud/anime/metal-rouge-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Metallic-Rouge-Sub-Indo.jpg",
    image_alt: "Metallic Rouge Sub Indo",
    date_release: "04 Apr",
    day_release: "None",
  },
  {
    title: "Sengoku Youko",
    link: "https://otakudesu.cloud/anime/sengoku-youko-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Sengoku-Youko.jpg",
    image_alt: "Sengoku Youko Sub Indo",
    date_release: "04 Apr",
    day_release: "None",
  },
  {
    title: "Shaman King: Flowers",
    link: "https://otakudesu.cloud/anime/shaman-king-flowers-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Shaman-King-Flowers-Sub-Indo.jpg",
    image_alt: "Shaman King Flowers Sub Indo",
    date_release: "04 Apr",
    day_release: "None",
  },
  {
    title: "Nanatsu no Taizai: Mokushiroku no Yonkishi",
    link: "https://otakudesu.cloud/anime/nanatsu-taizai-my-sub-indo/",
    episode: "Episode 24",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/10/Nanatsu-no-Taizai-Mokushiroku-no-Yonkishi.jpg",
    image_alt: "Nanatsu no Taizai: Mokushiroku no Yonkishi Sub Indo",
    date_release: "31 Mar",
    day_release: "None",
  },
  {
    title: "Shangri-La Frontier",
    link: "https://otakudesu.cloud/anime/shangri-frontier-sub-indo/",
    episode: "Episode 25",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/10/Shangri-La-Frontier.jpg",
    image_alt: "Shangri-La Frontier Sub Indo",
    date_release: "31 Mar",
    day_release: "Minggu",
  },
  {
    title: "Boku no Kokoro no Yabai Yatsu Season 2",
    link: "https://otakudesu.cloud/anime/boku-yabai-yatsu-s2-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/138581.jpg",
    image_alt: "Boku no Kokoro no Yabai Yatsu Season 2 Sub Indo",
    date_release: "31 Mar",
    day_release: "None",
  },
  {
    title: "Solo Leveling",
    link: "https://otakudesu.cloud/anime/solo-level-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Solo-Leveling.jpg",
    image_alt: "Solo Leveling Sub Indo",
    date_release: "31 Mar",
    day_release: "None",
  },
  {
    title: "Mashle Season 2",
    link: "https://otakudesu.cloud/anime/masle-s2-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Mshle-s2.jpg",
    image_alt: "Mashle Season 2",
    date_release: "31 Mar",
    day_release: "None",
  },
  {
    title: "Ragna Crimson",
    link: "https://otakudesu.cloud/anime/rag-crimson-sub-indo/",
    episode: "Episode 24",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/10/137709.jpg",
    image_alt: "Ragna Crimson Sub Indo",
    date_release: "31 Mar",
    day_release: "None",
  },
  {
    title: "Yuuki Bakuhatsu Bang Bravern",
    link: "https://otakudesu.cloud/anime/yuuki-bakuhatsu-ravern-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Yuuki-Bakuhatsu-Bang-Bravern.jpg",
    image_alt: "Yuuki Bakuhatsu Bang Bravern Sub Indo",
    date_release: "30 Mar",
    day_release: "None",
  },
  {
    title: "Chiyu Mahou no Machigatta Tsukaikata",
    link: "https://otakudesu.cloud/anime/chiyu-tsukaikata-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Chiyu-Mahou-no-Machigatta-Tsukaikata.jpg",
    image_alt: "Chiyu Mahou no Machigatta Tsukaikata Sub Indo",
    date_release: "30 Mar",
    day_release: "None",
  },
  {
    title: "Saijaku Tamer wa Gomi Hiroi no Tabi wo Hajimemashita.",
    link: "https://otakudesu.cloud/anime/saijaku-tamer-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Saijaku-Tamer-wa-Gomi-Hiroi-no-Tabi-wo-Hajimemashita..jpg",
    image_alt: "Saijaku Tamer wa Gomi Hiroi no Tabi wo Hajimemashita. Sub Indo",
    date_release: "30 Mar",
    day_release: "None",
  },
  {
    title: "Gekai Elise",
    link: "https://otakudesu.cloud/anime/gekai-elise-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Gekai-Elise.jpg",
    image_alt: "Gekai Elise Sub Indo",
    date_release: "28 Mar",
    day_release: "None",
  },
  {
    title: "Mahou Shoujo ni Akogarete",
    link: "https://otakudesu.cloud/anime/mahou-shoujo-akogarete-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/139414l.jpg",
    image_alt: "Mahou Shoujo ni Akogarete Sub Indo",
    date_release: "28 Mar",
    day_release: "None",
  },
  {
    title: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e Season 3",
    link: "https://otakudesu.cloud/anime/youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-s3-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Youkoso-Jitsuryoku-Shijou-Shugi-no-Kyoushitsu-e-Season-3-Sub-Indo.jpg",
    image_alt: "Classroom of the Elite III Sub Indo",
    date_release: "27 Mar",
    day_release: "None",
  },
  {
    title: "Jaku-Chara Tomozaki-kun Season 2",
    link: "https://otakudesu.cloud/anime/jaku-tomozaki-kun-s2-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Jaku-Chara-Tomozaki-kun.jpg",
    image_alt: "Jaku-Chara Tomozaki-kun S2 Sub indo",
    date_release: "27 Mar",
    day_release: "None",
  },
  {
    title: "Akuyaku Reijou Level 99",
    link: "https://otakudesu.cloud/anime/akuyaku-reijou-lv-99-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Akuyaku-Reijou-Level-99.jpg",
    image_alt: "Akuyaku Reijou Level 99 Sub Indo",
    date_release: "27 Mar",
    day_release: "None",
  },
  {
    title: "Loop 7-kaime no Akuyaku Reijou wa",
    link: "https://otakudesu.cloud/anime/loop-7-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Loop-7-kaime-no-Akuyaku-Reijou-wa.jpg",
    image_alt: "Loop 7-kaime no Akuyaku Reijou wa",
    date_release: "26 Mar",
    day_release: "None",
  },
  {
    title: "Momochi-san Chi no Ayakashi Ouji",
    link: "https://otakudesu.cloud/anime/momochisan-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2024/01/Momochi-san-Chi-no-Ayakashi-Ouji-Subtitle-Indonesia.jpg",
    image_alt: "Momochi-san Chi no Ayakashi Ouji Sub Indo",
    date_release: "23 Mar",
    day_release: "None",
  },
  {
    title: "Uma Musume: Pretty Derby Season 3",
    link: "https://otakudesu.cloud/anime/uma-musume-s3-sub-indo/",
    episode: "Episode 13",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/10/138948.jpg",
    image_alt: "Uma Musume: Pretty Derby Season 3 Sub Indo",
    date_release: "29 Des",
    day_release: "None",
  },
  {
    title: "Kizuna no Allele Season 2",
    link: "https://otakudesu.cloud/anime/kizuna-lele-s2-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/10/Kizuna-no-Allele-Season-2.jpg",
    image_alt: "Kizuna no Allele Season 2 Sub Indo",
    date_release: "21 Des",
    day_release: "None",
  },
  {
    title: "Shingeki no Kyojin: The Final Season - Kanketsu-hen",
    link: "https://otakudesu.cloud/anime/snk-final-part3-sub-indo/",
    episode: "Episode 2",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/03/Shingeki-no-Kyojin-The-Final-Season-Kanketsu-hen.jpg",
    image_alt: "Shingeki no Kyojin The Final Season - Kanketsu-hen Sub Indo",
    date_release: "06 Nov",
    day_release: "None",
  },
  {
    title: "Tensei shitara Slime Datta Ken: Coleus no Yume",
    link: "https://otakudesu.cloud/anime/tensei-shitara-slime-datta-coleus-yume-sub-indo/",
    episode: "Episode 3",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/11/Tensei-shitara-Slime-Datta-Ken-Coleus-no-Yume.jpg",
    image_alt: "Tensei shitara Slime Datta Ken: Coleus no Yume Sub Indo",
    date_release: "01 Nov",
    day_release: "None",
  },
  {
    title: "Nanatsu no Maken ga Shihai suru",
    link: "https://otakudesu.cloud/anime/nanatsu-ni-maken-sub-indo/",
    episode: "Episode 15",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/07/Nanatsu-no-Maken-ga-Shihai-suru.jpg",
    image_alt: "Nanatsu no Maken ga Shihai suru Sub Indo",
    date_release: "14 Okt",
    day_release: "None",
  },
  {
    title: "Synduality: Noir",
    link: "https://otakudesu.cloud/anime/synduality-nr-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/07/134806.jpg",
    image_alt: "Synduality: Noir Sub Indo",
    date_release: "26 Sep",
    day_release: "None",
  },
  {
    title: "Alice Gear Aegis Expansion",
    link: "https://otakudesu.cloud/anime/a-gear-expansion-sub-indo/",
    episode: "Episode 4",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2023/04/Alice-Gear-Aegis-Expansion-Sub-Indo.jpg",
    image_alt: "Alice Gear Aegis Expansion Sub Indo",
    date_release: "29 Apr",
    day_release: "None",
  },
  {
    title: "Urusei Yatsura (2022)",
    link: "https://otakudesu.cloud/anime/usura-2022-sub-indo/",
    episode: "Episode 12",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2022/10/129144.jpg",
    image_alt: "Urusei Yatsura (2022) Subtitle Indonesia",
    date_release: "15 Jan",
    day_release: "None",
  },
  {
    title: "Dragon Quest",
    link: "https://otakudesu.cloud/anime/dragon-the-quest-sub-indo/",
    episode: "Episode 100",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2020/10/Dragon-Quest-Sub-Indo.jpg",
    image_alt: "Dragon Quest Sub Indo",
    date_release: "22 Okt",
    day_release: "None",
  },
  {
    title: "Build Divide: Code White",
    link: "https://otakudesu.cloud/anime/build-dvide-cw-sub-indo/",
    episode: "Episode 9",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2022/04/121459.jpg",
    image_alt: "Build Divide: Code White Subtitle Indonesia",
    date_release: "08 Jun",
    day_release: "None",
  },
  {
    title: "Boruto",
    link: "https://otakudesu.cloud/anime/borto-sub-indo/",
    episode: "Episode 293",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2020/05/Boruto-Sub-Indo.jpg",
    image_alt: "Boruto Sub Indo",
    date_release: "12 Mei",
    day_release: "None",
  },
  {
    title: "Baraou no Souretsu",
    link: "https://otakudesu.cloud/anime/bns-sub-indo/",
    episode: "Episode 11",
    image_url: "https://otakudesu.cloud/wp-content/uploads/2022/01/118527.jpg",
    image_alt: "Baraou no Souretsu Subtitle Indonesia",
    date_release: "21 Mar",
    day_release: "None",
  },
];

const ITEMS_PER_PAGE = 24;

const Ongoing = () => {
  const [currentPage, setCurrentPage] = useState(1);

  // Calculate the number of pages needed
  const totalPages = Math.ceil(ongoingAnimes.length / ITEMS_PER_PAGE);

  // Get the items for the current page
  const currentItems = ongoingAnimes.slice((currentPage - 1) * ITEMS_PER_PAGE, currentPage * ITEMS_PER_PAGE);

  // Function to handle page changes
  const handlePageChange = (page) => {
    if (page < 1 || page > totalPages) return;
    setCurrentPage(page);
  };

  return (
    <>
      <div className="container min-h-[80vh] pt-20 pb-5 flex flex-col gap-5 items-center justify-center">
        {/* ONGOING */}
        <span className="container bg-gray-900 rounded-lg pb-5">
          <div className="flex items-center justify-start gap-2">
            <NavLink
              to={"/home"}
              className={"flex items-center justify-center pt-0.5"}>
              <i className="bx bx-chevron-left text-xl"></i>
            </NavLink>
            <h1 className="font-bold text-xl py-5">Anime Ongoing</h1>
          </div>

          <div className="flex gap-5 flex-wrap justify-center items-center">
            {currentItems.map((anime, index) => (
              <span
                className="flex gap-4 max-w-[25rem]"
                key={index}>
                {/* CARD */}
                <NavLink to={anime.link}>
                  <Card
                    className="w-[145px] h-[200px] hover:scale-105 transition-all transform duration-300 ease-in-out"
                    style={{
                      backgroundImage: `url(${anime.image_url})`,
                      backgroundSize: "cover",
                      backgroundPosition: "center",
                    }}></Card>
                </NavLink>
                {/* END CARD */}

                {/* CONTENT RIGHT CARD */}
                <div className="text-wrap max-w-[250px]">
                  <h1 className="font-semibold">{anime.title}</h1>
                  <p className="text-xs my-2 ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis aliquam officiis veritatis enim architecto reprehenderit nostrum minus animi harum ducimus error, laudantium eos repudiandae,
                    laboriosam in iste cum tempore tempora.
                  </p>
                  <ul className="flex items-center justify-start gap-3 mt-5">
                    <li className="flex items-center justify-center">
                      <i className="bx bx-play"></i>
                      <small>{anime.episode}</small>
                    </li>
                    <li className="flex gap-1 items-center justify-center">
                      <i className="bx bxs-calendar"></i>
                      <small>
                        {anime.date_release} - {anime.day_release}
                      </small>
                    </li>
                  </ul>
                </div>
                {/*END CONTENT RIGHT CARD */}
              </span>
            ))}
          </div>
        </span>
        {/* END ONGOING */}

        {/* PAGINATION */}
        <Pagination>
          <PaginationContent>
            <PaginationItem>
              <PaginationPrevious
                href="#"
                onClick={() => handlePageChange(currentPage - 1)}
                className={currentPage === 1 ? "hidden" : ""}
              />
            </PaginationItem>
            {Array.from({ length: totalPages }, (_, index) => (
              <PaginationItem key={index}>
                <PaginationLink
                  href="#"
                  isActive={index + 1 === currentPage}
                  onClick={() => handlePageChange(index + 1)}>
                  {index + 1}
                </PaginationLink>
              </PaginationItem>
            ))}
            <PaginationItem>
              <PaginationNext
                href="#"
                onClick={() => handlePageChange(currentPage + 1)}
                className={currentPage === totalPages ? "hidden" : ""}
              />
            </PaginationItem>
          </PaginationContent>
        </Pagination>
        {/* END PAGINATION */}
      </div>
    </>
  );
};

export default Ongoing;
